#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.


# chkconfig:   2345 90 10
# description:  Redis is a persistent key-value database

REDISPORT={{redisport}}
#EXEC=/usr/local/bin/redis-server
EXEC={{homedir}}/{{bimapuser}}/bimap/opt/redis-{{redisVersion}}/src/redis-server
#CLIEXEC=/usr/local/bin/redis-cli
CLIEXEC={{homedir}}/{{bimapuser}}/bimap/opt/redis-{{redisVersion}}/src/redis-cli

PIDFILE={{homedir}}/{{bimapuser}}/bimap/run/redis_${REDISPORT}.pid
#CONF="/etc/redis/${REDISPORT}.conf"
CONF={{homedir}}/{{bimapuser}}/bimap/conf/redis_{{redisport}}.conf

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redis server..."
                $EXEC $CONF &
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $REDISPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis to shutdown ..."
                    sleep 1
                done
                echo "Redis stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
